openapi: 3.0.0
info:
  title: RAG Agent API
  version: 1.0.0
  description: API for interacting with the RAG Agent to answer natural language questions.
servers:
  - url: /
    description: Local development server
paths:
  /query:
    post:
      summary: Query the RAG Agent
      description: Sends a natural language question to the RAG Agent and receives an answer with references.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response with the answer and references.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '400':
          description: Bad request, e.g., empty question.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
components:
  schemas:
    QueryRequest:
      type: object
      required:
        - question
      properties:
        question:
          type: string
          description: The natural language question from the user.
          example: "What is the capital of France?"
    AgentResponse:
      type: object
      required:
        - answer
        - references
      properties:
        answer:
          type: string
          description: The coherent answer generated by the agent.
          example: "The capital of France is Paris."
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
    Reference:
      type: object
      required:
        - url
        - heading
      properties:
        url:
          type: string
          description: The URL of the source document.
          example: "https://example.com/paris-facts"
        heading:
          type: string
          description: A relevant heading or title from the source.
          example: "Facts About Paris"
